### ISSUE TITLE
feat: marianzburlea - create skills section

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/my-cv-v3-starter#14]
* [x] feat: marianzburlea - create legend list for skills #15 
* [x] feat: marianzburlea - add title and skill list #16
* [ ] feat: marianzburlea - create finish content indicator #17
