### ISSUE TITLE
feat: marianzburlea - create welcome section

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/my-cv-v3-starter#4]
* [x] feat: marianzburlea - create the title and subtittle #5
* [x] feat: marianzburlea - create a section title and a box with shadow #6 
* [x] feat: marianzburlea - create download button #7 
* [x] feat: marianzburlea - create continue indicator #13
