### ISSUE TITLE
feat: mariateo - add welcome section

### ISSUE THREAD

**Issue by MariaTeo** [codetapacademy/my-cv-v3-starter#63]
* [x]  feat: mariateo - add the title and subtitle #64 
* [x]  feat: mariateo - add a section title and a box with shadow #65 
* [x]  feat: mariateo - add download button #66 
* [x]  feat: mariateo - add arrow down #67
