### ISSUE TITLE
feat: marianzburlea - create connect section

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/my-cv-v3-starter#8]
* [x] feat: create section title for connect #9 
* [x] feat: add image with rounder corners and border #10
* [x] feat: add list of icons and link to social media #11
* [x] feat: add continue indicator #12
